# -*- coding: utf-8 -*-
{
    'name': "Orchid ASPGulf",

    'summary': """Customized Module for ASPGulf""",
    'author': "OrchidERP",
    'website': "http://www.orchiderp.com",
    'category': 'Uncategorized',
    'version': '0.1',

    # any module necessary for this one to work correctly
    'depends': ['base','sale','sale_management','crm','sale_crm','orchid_revision_v14','account','orchid_account_enhancement_v14'],

    # always loaded
    'data': [
        'views/contract_seq.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/data.xml',
        'views/revenue_forecast_assets.xml',
        'views/asp_groups.xml',
        'views/product.xml',
        'wizards/lead_assign_user.xml',
        'wizards/advance_contract_invoice.xml',
        'wizards/terminate_contract_line.xml',
        'wizards/renew_contract.xml', 
        'wizards/merge_revenue.xml', 
        'views/contract.xml',
        'views/partner.xml',
        'views/contract_payment.xml',
        'views/sale.xml',
        'views/purchase.xml',
        'views/crm.xml',
        'views/account_move.xml',
        'views/provision_masters.xml',
        'views/provision_form_view.xml',
        'wizards/multiple_contract_invoice.xml', 
        'wizards/revenue_recognition.xml', 
        'wizards/revenue_recognition_report.xml', 
        'views/fluctuating_contract.xml', 
        'views/cost_booking.xml', 
        'wizards/contract_revenue_report.xml', 
        'views/cash_bank.xml', 
        'views/product_correction_utility.xml', 
        # 'wizards/contract_credit_note.xml', 
        'views/menus.xml',
        
        # 'reports/usd_sale_print.xml',
        'reports/asp_sale_print.xml',
        'reports/asp_tax_invoice_print.xml',
        'reports/asp_tax_invoice_print_aed.xml',
        'reports/asp_usd_vat_print.xml',
        # 'reports/aed_sale_print.xml',
        # 'reports/usd_proforma_print.xml',
        # 'reports/aed_proforma_print.xml',
        'reports/sale_paper_format.xml',
        'reports/contract_analysis_report.xml',
        'reports/purchase_costing.xml',
        'reports/revenue_line_view.xml',
        'reports/purchase_requisition.xml',
        'reports/purchase_order.xml',
        'reports/contract_revenue_report.xml',
        'reports/revenue_recognition_report.xml',
        'views/revenue_forecast_report.xml',
        'reports/report_enbd_cheque_print.xml',
        'reports/report_fab_cheque_print.xml',
        # 'reports/usd_sale_option_print.xml',
        # 'reports/aed_sale_option_print.xml',
        'reports/menu.xml',
        'views/schedule_actions.xml',
        
    ],
    'qweb': [
        'static/src/xml/revenue_forecast_report.xml',
    ],
    
}
