# -*- coding: utf-8 -*-
{
    'name': "Orchid Somfy KSA",

    'summary': """OrchidERP Customized for Somfy""",

    'author': "OrchidERP",
    'website': "https://www.orchiderp.com",

    # Categories can be used to filter modules in modules listing
    # Check https://github.com/odoo/odoo/blob/16.0/odoo/addons/base/data/ir_module_category_data.xml
    # for the full list
    'category': 'Uncategorized',
    'version': '0.1',

    # any module necessary for this one to work correctly
    'depends': ['base','account','stock','sale','product','sale_stock','purchase','stock_dropshipping','l10n_sa','purchase_stock','l10n_sa','orchid_stock_reservation_v16','orchid_account_enhancement_v16','account_accountant','orchid_budget_v16','sale_margin','stock_landed_costs','account_asset','hr_expense','hr_attendance','hr_payroll_account','hr_holidays','hr_work_entry_contract_enterprise'],

    # always loaded
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/product_data.xml',
        'data/email_template.xml',
        'data/payslip_email_template.xml',
        'data/ir_config.xml',
        'data/ir_cron.xml',
        # 'views/account_opening_form_notification.xml',
        'views/user.xml',
        'views/partner_masters.xml',
        'views/local_transport_charge_master.xml',
        'views/cbm_rate.xml',
        'views/partner_view.xml',
        'views/product.xml',
        'views/product_masters.xml',
        'views/account.xml',
        'views/stock.xml',
        'views/stock_picking.xml',
        'wizard/margin_reason.xml',
        'views/sale.xml',
        'views/purchase_order.xml',
        'views/purchase_enquiry.xml',
        'views/purchase_return.xml',
        'views/volume_rebate.xml',
        'views/old_erp.xml',
        'views/account_invoice.xml',
        'views/product_price_change.xml',
        'views/salary_provision.xml',
        'wizard/approval_wiz.xml',
        'wizard/pricelist_price_change_refuse.xml',
        'views/account_opening_form.xml',
        'views/product_opening_form.xml',
        'views/pricelist_price_change.xml',
        'views/stock_adjustment.xml',
        'views/hr_expense.xml',
        'views/hr_contract_view.xml',
        'pricelist/product_pricelist.xml',
        # 'views/salary_entries.xml',
        'views/menu.xml',
        'reports/report_external_layout_striped.xml',
        'reports/report_commercial_invoice.xml',
        'reports/report_ksa_sale_order.xml',
        'reports/report_delivery_slip.xml',
        'reports/report_packing_list.xml',
        # 'reports/report_hscode.xml',
        # 'reports/report_delivery_advice.xml',
        # 'reports/report_tax_invoice.xml',
        'reports/report_service_invoice.xml',
        'reports/report_service_invoice_sar.xml',
        'reports/report_sale_order.xml',
        'reports/report_purchase_order.xml',
        'reports/report_grn.xml',
        'reports/report_purchase_enquiry.xml',
        'reports/report_account_payment_voucher.xml',
        'reports/report_asset_statement.xml',
        'reports/landed_cost_analysis.xml',
        'reports/report_hr_expense.xml',
        'reports/reports.xml',
        'reports/report_template.xml',
        'wizard/gulf_sale_upload.xml',
        'wizard/sales_register.xml',
        'wizard/pl_report.xml',
        'wizard/balance_sheet.xml',
        'wizard/discount_report.xml',
        'wizard/threes_report_view.xml',
        'wizard/customer_info_report.xml',
        'wizard/pricing_report.xml',
        'wizard/account_change_lock_date.xml',
        'wizard/create_po_from_enquiry.xml',
        'wizard/stock_aging_report.xml',
        'wizard/dso_dio_report.xml',
        'wizard/slow_stock_report.xml',
        'wizard/stock_report.xml',
        'wizard/vat_declaration_report.xml',
        'wizard/asset_report.xml',
        'wizard/asset_depreciation_post.xml',
        'views/budget.xml',
        'views/budget_analysis.xml',
        'views/product_opening_form_batch.xml',
        'views/attendance_email_template.xml',
        'views/expense_batch.xml',
        'views/contract_renewal.xml',

    ],
    
}
